Sidebar responsiveness fix
lblod/frontend-contactgegevens-loket pull request #26
Opened 2023-11-15 12:37 UTC by andreo141

## ID
[CLBV-216](https://binnenland.atlassian.net/browse/CLBV-216)

 ## Description

Sidebar was not responsive when displayed on smaller screens. 

 ## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Other

 ## How to test

Resize the window to test the responsiveness of the sidebar container and the breadcrumb trail

2023-11-15 16:06 UTC, lagartoverde requested changes
Make a component is better, then we can add it to new pages and we are not repeating code

2023-11-15 16:06 UTC, lagartoverde commented on app/templates/core-data.hbs
You can extract this to a component, and then you are not repeating the same code in both pages

2023-11-17 10:59 UTC, lagartoverde requested changes
![image](https://github.com/lblod/frontend-contactgegevens-loket/assets/17006446/da8657c9-2335-428c-b778-42f1eff402ed)
Now my login looks like this xd
![image](https://github.com/lblod/frontend-contactgegevens-loket/assets/17006446/4b4df4d7-f7ba-4756-ac38-3bf5e7a16ce6)
Also on this screen we have a new scroll bar that we don't need
![image](https://github.com/lblod/frontend-contactgegevens-loket/assets/17006446/c181da73-a746-4308-a1ea-1a63c3603f8c)
And still the responsiveness of the menu is not ideal

2023-11-21 08:33 UTC, andreo141 commented
I will make a new PR with the new login page. Will close this one.

2023-11-21 08:33 UTC, closed without merging