deleted the modal for warnings
lblod/frontend-contactgegevens-loket pull request #38
Opened 2023-11-28 10:03 UTC by YJouhar47

After clicking the second time while getting a warning, it will save instead of the modal and then clicking ys

2023-11-28 11:05 UTC, andreo141 requested changes

2023-11-28 11:05 UTC, andreo141 commented on app/controllers/sites/new.js
> +  @tracked buttonCounter = 0;
Zou deze variable misschien beter iets als saveButtonPressed noemen. Is duidelijker dan over welke button het gaar.

2023-11-28 11:05 UTC, andreo141 commented on app/controllers/sites/new.js
> +      if (this.buttonCounter == 2) {
Hier ook beter een strict equal gebruiken (===)

2023-11-28 11:22 UTC, andreo141 approved these changes
Looks good :)

2023-12-15 13:13 UTC, merged

2023-12-15 14:38 UTC, DennisVanEecke commented on app/components/error/save.hbs
Wut?? This is barely worth using a component for. Also an entire component wrapped in an if just is not transparant to the user of the components.
Unless you want to expand this in the future; delete error/save and error/warning and just use AuHelpText where you need.

2023-12-15 14:38 UTC, DennisVanEecke commented on app/components/error/warning.hbs
See comment on error/save

2023-12-15 14:38 UTC, DennisVanEecke commented on app/controllers/sites/new.js
>        if (this.saveButtonPressed === 2) {
Zet saveButtonPressed terug op 0. Controllers blijven leven in je ember app. Dus 't kan zijn dat je bij de volgende keer dat je op de page komt je value 2 is en niet 0

2023-12-15 14:38 UTC, DennisVanEecke commented on app/controllers/sites/new.js
> +      console.log('Dit is je warning', this.hasWarning);
Remove console log. Zet deze lijn: `this.validationWarnings = validationResult.warnings;` in de plek

2023-12-15 14:38 UTC, DennisVanEecke commented on app/styles/_shame.scss
> +.au-c-button-group {
Onnodig. Identieke class bestaat al `.au-u-flex--end`